"""Generate the Supplementary tables from the released JSON records.

The tables are *generated*, never typed, so the Supplementary Information cannot disagree
with the released records. This is the same principle as verify_numbers.py: the manuscript's
claim that every quoted number is regenerated by the build is only true if the tables are
built that way too.

Three tables are emitted into one file:
  Table S1  disturbance-bound sweep  -- the empirical test of Lemma 1
  Table S2  reward-scale and penalty-weight sweeps -- the knobs that do not fix leakage

Table S1's predicted column is computed from Lemma 1 (non-vacuous iff a_max > eps_max),
not read from the data, so a disagreement between prediction and measurement is visible in
the table rather than hidden by it.

Run:  python make_sweep_table.py [--outdir results] [--out ../manuscript/supplementary_sweep_table.tex]
"""

import argparse
import json
import math
import os


def f3(x):
    return "%.3f" % x


def pct(x, digits=1):
    """'84.1\\%' -- x already in percent. The format string must be applied to x;
    returning it unapplied writes literal '%.1f\\%' into the Supplementary tables."""
    return (("%." + str(digits) + "f") % x) + r"\%"


def comma(n):
    return "{:,}".format(int(n))


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--outdir", default="results")
    ap.add_argument("--out", default=os.path.join("..", "manuscript",
                                                  "supplementary_sweep_table.tex"))
    args = ap.parse_args()

    summary = json.load(open(os.path.join(args.outdir, "summary.json")))
    a_max = summary["config"]["a_max"]
    eps = sorted(json.load(open(os.path.join(args.outdir, "sweep_eps_max.json"))),
                 key=lambda r: r["value"])
    rs = sorted(json.load(open(os.path.join(args.outdir, "sweep_reward_scale.json"))),
                key=lambda r: r["value"])
    lam = sorted(json.load(open(os.path.join(args.outdir, "sweep_lambda.json"))),
                 key=lambda r: r["value"])

    n_seeds = eps[0].get("train_seeds")
    n_runs = eps[0].get("sweep_runs")
    steps = eps[0].get("abmdp_evaluated_steps")

    L = []
    # ------------------------------------------------------------------ Table S1
    L.append(r"\begin{table}[htbp]")
    L.append(r"\centering")
    L.append(r"\caption{\textbf{The disturbance-bound sweep tests the threshold of "
             r"Lemma~1 rather than assuming it.} "
             r"Each row re-trains the penalty baseline and the filtered agent from scratch "
             r"at the stated $\epsilon_{\max}$, with $a_{\max} = %s$ fixed; %d independent "
             r"training seeds and %s evaluation episodes per seed, giving %s evaluated "
             r"steps for the filtered agent per row. The second column is the prediction of "
             r"Lemma~1 alone, computed from the inequality and not from the measurements. "
             r"``Vacuous'' counts steps on which $\mathcal{A}(s) = \emptyset$ was detected "
             r"from the sign of $m(s)$ before acting, the agent then applying the maximally "
             r"inward action; breaches are attributed by whether the step that produced them "
             r"was vacuous.}"
             % (f3(a_max), n_seeds, comma(n_runs), comma(steps)))
    L.append(r"\label{tab:sweep_eps}")
    L.append(r"\vspace{0.4em}")
    L.append(r"\small")
    L.append(r"\setlength{\tabcolsep}{5pt}")
    L.append(r"\begin{tabular}{@{}rrrrrrr@{}}")
    L.append(r"\toprule")
    L.append(r"$\epsilon_{\max}$ & Lemma~1: & Penalty & AB-MDP & Vacuous & Breaches on & "
             r"Breaches on \\")
    L.append(r" & non-vacuous? & breach rate & breach steps & steps (\%) & vacuous steps & "
             r"non-vacuous \\")
    L.append(r"\midrule")
    for r in eps:
        v = r["value"]
        L.append(" & ".join([
            f3(v),
            "yes" if a_max >= v else r"\textbf{no}",
            pct(100 * r["penalty_breach_rate"]),
            comma(r["abmdp_breach_steps_total"]),
            pct(100 * r.get("abmdp_vacuous_step_frac", 0.0)),
            comma(r.get("abmdp_vacuous_breach_steps", 0)),
            comma(r.get("abmdp_breach_steps_on_nonvacuous", r["abmdp_breach_steps_total"])),
        ]) + r" \\")
    L.append(r"\bottomrule")
    L.append(r"\end{tabular}")
    L.append(r"\end{table}")
    L.append("")

    # ------------------------------------------------------------------ Table S2
    tab1_end = len(L)
    L.append(r"\begin{table}[htbp]")
    L.append(r"\centering")
    L.append(r"\caption{\textbf{Neither the reward scale nor the penalty weight removes "
             r"leakage.} "
             r"Top block: reward scale varied with $\lambda = 10$ fixed. Bottom block: "
             r"penalty weight varied with $\bar{R} = 2$ fixed. Same seeds and episode "
             r"counts as Table~S1. A run is counted as leaky if it breaches in at least "
             r"half of its evaluation episodes; the interval is exact (Clopper--Pearson, "
             r"95\%). The filtered agent recorded zero breach steps in every row of both "
             r"blocks.}")
    L.append(r"\label{tab:sweep_knobs}")
    L.append(r"\vspace{0.4em}")
    L.append(r"\small")
    L.append(r"\setlength{\tabcolsep}{5pt}")
    L.append(r"\begin{tabular}{@{}rrrrr@{}}")
    L.append(r"\toprule")
    L.append(r"Swept value & Penalty breach rate & population s.d.\ across seeds & Leaky runs & "
             r"Exact 95\% interval \\")
    L.append(r"\midrule")
    L.append(r"\multicolumn{5}{@{}l}{\emph{Reward scale $\bar{R}$, with $\lambda = 10$}} \\")
    for r in rs:
        lo, hi = r["penalty_leaky_runs_frac_ci95_exact"]
        L.append(" & ".join([
            f3(r["value"]),
            pct(100 * r["penalty_breach_rate"]),
            pct(100 * r["penalty_breach_rate_std"]),
            "%d/%d" % (r["penalty_leaky_runs"], r["train_seeds"]),
            r"$[%s, %s]$" % (pct(100 * lo), pct(100 * hi)),
        ]) + r" \\")
    L.append(r"\addlinespace")
    L.append(r"\multicolumn{5}{@{}l}{\emph{Penalty weight $\lambda$, with "
             r"$\bar{R} = 2$}} \\")
    for r in lam:
        lo, hi = r["penalty_leaky_runs_frac_ci95_exact"]
        L.append(" & ".join([
            f3(r["value"]),
            pct(100 * r["penalty_breach_rate"]),
            pct(100 * r["penalty_breach_rate_std"]),
            "%d/%d" % (r["penalty_leaky_runs"], r["train_seeds"]),
            r"$[%s, %s]$" % (pct(100 * lo), pct(100 * hi)),
        ]) + r" \\")
    L.append(r"\bottomrule")
    L.append(r"\end{tabular}")
    L.append(r"\end{table}")

    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    # Table S2 goes to its own file so each Note can \input exactly the table it
    # discusses; a single shared file would force the order of the Notes.
    knob_out = os.path.join(os.path.dirname(os.path.abspath(args.out)),
                            "supplementary_knob_table.tex")
    with open(args.out, "w", encoding="utf-8") as f:
        f.write("\n".join(L[:tab1_end]) + "\n")
    with open(knob_out, "w", encoding="utf-8") as f:
        f.write("\n".join(L[tab1_end:]) + "\n")
    print("wrote %s: table S1 (%d rows)" % (args.out, len(eps)))
    print("wrote %s: table S2 (%d + %d rows)" % (knob_out, len(rs), len(lam)))

    # Consistency check: Lemma 1 predicts vacuity nowhere in K exactly when
    # eps_max <= a_max (non-strict -- see the module docstring on the boundary case).
    # If the sweep ever contradicts the lemma, the caller must see it here rather than in
    # a referee report.
    bad = [(r["value"], r.get("abmdp_vacuous_steps_total", 0))
           for r in eps
           if (a_max >= r["value"]) != (r.get("abmdp_vacuous_steps_total", 0) == 0)]
    if bad:
        print("WARNING: Lemma 1 prediction and measured vacuity disagree at "
              "(eps_max, vacuous_steps) = %s" % bad)
        return 1
    print("consistency: Lemma 1 prediction agrees with measured vacuity at all %d points"
          % len(eps))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
